feat: create-shadow-code
balckowl/nextjs-hackthon pull request #12
Opened 2024-10-15 10:09 UTC by hayatonanba

## チェック
- [x] 余計な差分は存在しないか？

## 実装内容
box-shadowのコード部分を記載

## スクショ
<img width="1440" alt="スクリーンショット 2024-10-15 19 09 19" src="https://github.com/user-attachments/assets/149f10b7-881d-4097-bde5-594126685a38">

## issue
close 

## 懸念点

2024-10-15 10:48 UTC, balckowl requested changes

2024-10-15 10:48 UTC, balckowl commented on src/app/box-shadow/page.tsx
> +            box-shadow: {boxShadowx}px {boxShadowy}px {boxShadowb}px {boxShadows}px {boxColor};<br />
boxShadowが定義されているので、それでいいんじゃないんですか？
tailwindのコードも一旦変数に入れた方が綺麗な気がします。

2024-10-15 10:51 UTC, hayatonanba commented on src/app/box-shadow/page.tsx
> +            box-shadow: {boxShadowx}px {boxShadowy}px {boxShadowb}px {boxShadows}px {boxColor};<br />
うい〜

2024-10-16 07:02 UTC, balckowl approved these changes
LGTM

2024-10-16 07:02 UTC, balckowl commented on src/app/box-shadow/page.tsx
> +            box-shadow: {boxShadowx}px {boxShadowy}px {boxShadowb}px {boxShadows}px {boxColor};<br />
変わってなくない？
普通のCSSの方

2024-10-16 07:03 UTC, merged